# When something is pushed to master, rebuild the docs
name: deploy-vuepress-site

on:
  push:
    branches:
    - main-built

env:
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    if: github.repository == 'FrontEndFoxes/curriculum'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: 'npm install'
      run: npm install
    - name: 'Build the docs with VuePress'
      run: ./deploy.sh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./src/.vuepress/dist
        user_name: 'jlooper'
        user_email: 'jen@ladeezfirstmedia.com'