name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: frontendfoxes/curriculum
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: .vuepress/dist
